[OpenAI]
base_url = "https://api.deepseek.com"
model = "deepseek-v4-flash-vision-exp"
tool = true     # 是否启用工具调用
reasoning_effort = "high"   # 思考强度，可选值为 low、high、max
extra_body = {thinking = {type = "enabled"}}    # 参考各服务商API指南进行配置
think_output = true      # 是否启用思考输出，仅开启思考模式时有效。注意：会在<think></think>块中显式输出思考内容

api_key = [
    "",
    ""
    # 像这样添加多个API_KEY。记得带逗号！
]

[OpenAI.env]
env = true     # 是否使用环境变量中的API_KEY，若使用，则上方的[OpenAI.api_key]配置无效

api_key_name = [
    "TEST_API_KEY",
    ""
    # 像这样添加多个API_KEY的名称
]

[OnlineSearch]  # 联网搜索API配置
enable = true   # 是否启用联网搜索

base_url = "https://qianfan.baidubce.com/v2/ai_search/web_search"   # 仅支持百度千帆————大概吧，其他的自己试试
# 先看下方注释
api_key = [
    "",
    ""
    # 像这样添加多个API_KEY
]
# 若启用了[OpenAI.env]，则同样需要在环境变量中配置联网搜索的API_KEY_NAME，上方的API_KEY配置无效
api_key_name = [
    "TEST_SEARCH_API_KEY",
    ""
    # 像这样添加多个API_KEY的名称
]

[TTS]   # 语音合成API配置
enable = true   # 是否启用语音合成，仅支持火山引擎

api_key = [
    "",
    ""
    # 像这样添加多个API_KEY
]

# 同上
api_key_name = [
    "TEST_TTS_API_KEY",
    ""
    # 像这样添加多个API_KEY的名称
]

model = "seed-tts-2.0"   # 语音合成模型

speaker = ""   # 语音合成音色id