[Identity]  # 仅供显示，不影响对话
user_name = "User"    # 用户名称
assistant_name = "Assistant"    # 助手名称

[Images]     # 图片配置
upload = true  # 是否启用图片上传功能。仅多模态模型支持，非多模态模型使用会报错
# 支持图片类型：jpg、jpeg、png、gif（动态仅提取首帧）、webp（动态仅提取首帧）

Files_API = true  # 采用Files API上传图片，会比通常模式保存的图片多。上一个配置项开启时有效
# 请确保使用的模型所属的服务商支持OpenAI SDK的Files API
# 此处提供一部分服务商的参考支持情况：
# OpenAI：支持，但需手动开启功能，图片储存额外付费。参考费用：$0.20/GB/月
# DeepSeek：支持，上传图片与储存服务免费
# 阿里云百炼（通义千问）：支持，上传图片与储存服务免费
# 火山方舟（豆包Seed系列）：支持，上传图片与储存服务免费。注意：豆包原生API不支持OpenAI SDK兼容的Files API
# 智谱AI：不支持
# 百度千帆（文心一言）：不支持
# Kimi：不支持
# MiniMax：不支持
# 其他平台请自行查阅API文档

[Voice]  # 语音合成配置。若未在API配置中开启TTS，则此处配置无效
speed = 0  # 语速，范围[-50, 100]，默认0为1倍速，100为2倍速，-50为0.5倍速，以此类推
loudness = 0  # 音量，范围[-50, 100]，默认0为正常音量，100为2倍音量，-50为0.5倍音量，以此类推
pitch = 0  # 音调，范围[-12, 12]，默认0为正常音调，越高声音越尖锐，越低声音越低沉

max_length_to_filter_parenthesis = 50   # 过滤括号内内容的最大长度，超过该长度的括号内内容将不会被过滤。若设置为0，则不进行过滤。建议范围为0~100，除不能为负外无强制要求

[Confirm]   # 是否需要确认Agent操作
view_file = false  # 查看文件内容
append_file = true  # 向文件末尾添加内容
overwrite_file = true  # 覆盖文件内容
create_file = false  # 创建新文件或目录
move_file = true  # 移动文件或目录
copy_file = true  # 复制文件或目录
rename_file = false  # 重命名文件或目录
get_file_info = false  # 获取文件或目录信息
search_file = false  # 搜索文件或目录
view_files_list_recursive = true  # 查看目录下的所有文件列表，包括子目录


overwrite_docx = true  # 是否需要确认Agent对docx文件的编辑操作。
# 注意！Agent向docx文件写入内容时，会破坏原有的特殊格式（如页眉页脚）和字号间距等。请修改docx_example里的模板文件以达到理想效果

# 以下配置禁止更改
view_files_list = false  # 查看文件列表
delete = true  # 删除文件
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# 骗你的，随便改，改了也没用，删了都可以。你问没用为什么放在这里？
# 因为有些东西是命中注定不可更改的
# 我是说：就是逗你玩的