[Memory]    # 记忆配置。上传的图片会随历史记录的清理一并删除
max_history_days = 7  # 设定历史对话最长保存天数，超过此天数的历史对话将被删除（建议值：5 ~ 14）
max_history_tokens = 64000  # 设定历史对话最长保存token数，超过此token数后，最早一天的历史对话将被删除（建议值：50000 - 100000）
# 注意！仅包含历史对话的tokens,本轮对话不包括在内，因此实际消耗会比此值略高
# 删除后，历史对话将变为记忆。若想让Agent想起，请主动提及
